-- AlterTable
ALTER TABLE "users" ADD COLUMN     "city" TEXT,
ADD COLUMN     "goal_daily" DOUBLE PRECISION NOT NULL DEFAULT 1500,
ADD COLUMN     "goal_monthly" DOUBLE PRECISION NOT NULL DEFAULT 30000,
ADD COLUMN     "goal_weekly" DOUBLE PRECISION NOT NULL DEFAULT 8000,
ADD COLUMN     "phone" TEXT,
ADD COLUMN     "profile_photo" TEXT;
